### ISSUE TITLE
More gamification needed

### ISSUE THREAD

**Issue by rromanw** [plbrault/youre-the-os#61]
When I play the game, I get frustrated over time that I can't manage the game anymore and the time reward is not enough. I'd be happy if there was something like tetris levels. I could track my progress that I can sustain for example level 6 indefinitely and on level 7 I can last only 2 minutes or so. Further "level up" cues would be awesome too.

Also for my purposes, I'd like to have  the option to make the tiles smaller. I'm having troubles with my mouse accuracy and would like to improve it in this game.

**Comment by plbrault** [comment]
I'm planning to add some kind of "Arcade mode" in the future that would be basically what you described.

**Comment by plbrault** [comment]
See [this comment](https://github.com/plbrault/youre-the-os/issues/112#issuecomment-2094916586) for a new "story mode" I am planning for the game.

**Comment by plbrault** [comment]
See https://github.com/plbrault/youre-the-os/issues/112#issuecomment-2094916586 for a new "story mode" I am planning for the game.
