### ISSUE TITLE
[Feature Request] Autoplay

### ISSUE THREAD

**Issue by MrThanlon** [plbrault/youre-the-os#70]
Writing code to autoplay.

**Comment by BeiyanYunyi** [comment]
I have a version. https://github.com/BeiyanYunyi/youre-the-os

Since I'm not a computer science major, I don't think the algorithm in my code is a good solution.

**Comment by Wiguwbe** [comment]
Exactly my thought!

I did implement a feature to allow the user to provide a script, check #75
